name: Events Demo 1
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev-*' # on branches like dev-1, dev-demo, dev-demo-select-task
      - 'feature/**' # any branch with feature and containing / or not eg: feature/primary, feature/demo/post
  push:
    branches:
      - main
      - 'dev-*' # on branches like dev-1, dev-demo, dev-demo-select-task
      - 'feature/**' # any branch with feature and containing / or not eg: feature/primary, feature/demo/post
      - 'feat/**'
      # will not run workflow in case of branch of name like developer-1 i.e. other than the defined branch patterns
    paths-ignore:
      - './github/workflows'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."